### PR TITLE
gh-pages: drop the old docs

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Should we also remove the `gh-pages` branch?

**Comment by GuillaumeGomez** [comment]
(that would have been simpler haha)

**Comment by bilelmoussaoui** [comment]
> Should we also remove the `gh-pages` branch?

Not really, it contains the new docs under `git/docs` subdirectory :p

**Comment by bilelmoussaoui** [comment]
& in the future stable/docs as well

**Pull request merged**
