### PR TITLE
Remove dox

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Based on https://github.com/gtk-rs/gir/pull/1005.

Everything seems to be working as expected?

### CODE REVIEW

**Comment by sdroege** [comment]
> Everything seems to be working as expected?

Well, the CI fails :)

```
`#[doc(cfg)]` is experimental
```

and

```
 error[E0432]: unresolved import `ffi::winapi`
Error:  --> cairo/src/win32_surface.rs:5:9
  |
5 | pub use ffi::winapi;
  |         ^^^^^^^^^^^ no `winapi` in the root
```

Otherwise seems good to me once that is fixed.

Can you also submit an MR for that to gstreamer-rs?

**Comment by GuillaumeGomez** [comment]
I forgot to rebuild gir before the regen...

**Comment by sdroege** [comment]
Please update gir another time before this to also get the other changes included

**Comment by GuillaumeGomez** [comment]
I created an issue about this situation: https://github.com/gtk-rs/gir/issues/1009

Closing until fixable...

**Pull request closed without merging**
