### PR TITLE
Make DateTime Option returns into Result

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/gtk-rs/gtk-rs/issues/196.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Funny bug in gir generation. :3

**Comment by sdroege** [comment]
CI says no :)

**Review by sdroege — APPROVED** [review]
lgtm otherwise

**Comment by GuillaumeGomez** [comment]
Updated!

**Review by sdroege — APPROVED** [review]

**Pull request merged**
