### PR TITLE
Mark 'key' parameter nullable for KeyFile's get_comment()

### PR DESCRIPTION
**Pull request by sdroege**
See https://github.com/gtk-rs/gtk-rs/pull/284

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sdroege** [comment]
Unclear why this didn't happen automatically though, looks like we also have a gir bug here:

```xml
          <parameter name="group_name" transfer-ownership="none" nullable="1" allow-none="1">
            <doc xml:space="preserve">a group name, or %NULL</doc>
            <type name="utf8" c:type="const gchar*"/>
          </parameter>
```

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gir/issues/1046

**Comment by sdroege** [comment]
Oh nevermind, that's the wrong parameter.

**Comment by sdroege** [comment]
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1915

**Pull request merged**
