### PR TITLE
gio: Mark ETag out parameter in various GFile functions as nullable

### PR DESCRIPTION
**Pull request by sdroege**
See https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1956

Fixes https://github.com/gtk-rs/gtk-rs/issues/305

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez Any ideas why gir doesn't actually make use of this? :)

**Comment by GuillaumeGomez** [comment]
Very likely because it wasn't implemented... Do you need the `name` field for a return parameter?

**Comment by sdroege** [comment]
> Very likely because it wasn't implemented... Do you need the `name` field for a return parameter?

This is an out parameter. Ok, I'll investigate...

**Comment by sdroege** [comment]
I think because the parameter analysis happens *after* creating the bounds...

**Comment by sdroege** [comment]
`src/analysis/functions.rs:analyze_callbacks()` is the problem. It first calls `bounds.add_for_parameter()` and only at the bottom calls `function_parameters::analyze()`.

**Comment by sdroege** [comment]
Or maybe not. The same code is called in many different places in slightly different ways...

**Review by bilelmoussaoui — APPROVED** [review]

**Review by GuillaumeGomez — APPROVED** [review]

**Pull request merged**
