### PR TITLE
migration cleanup

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
One thing I've noticed is that each crate had a different readme, we could probably try to expose the list of features there, a quick link to the crates.io/docs for the specific crate and probably the C/upstream projects links.

### CODE REVIEW

**Comment by sdroege** [comment]
Yes making them consistent would be useful. What you suggest makes sense to me

**Comment by bilelmoussaoui** [comment]
Right, I will try to do what I have in mind for a specific crate and see how that goes.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
This was not finished yet :P

**Comment by bilelmoussaoui** [comment]
Can be done separately :P

**Comment by bilelmoussaoui** [comment]
I should have probably tagged it as WIP to avoid such situations in the future ^^

**Comment by GuillaumeGomez** [comment]
Arf sorry. >< Based on the code I just assumed it was, my bad.

**Pull request merged**
