### PR TITLE
Remove optional $rust_class_name argument from glib_wrapper!

### PR DESCRIPTION
**Pull request by ids1024**
This is possible now that Gir is updated.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Was the removal of the optional name handled by gir ? I can't seem to get them removed by regenerating the gtk4-rs crates

**Comment by ids1024** [comment]
https://github.com/gtk-rs/gtk-rs/pull/10 made `$rust_class_name` optional (and make the class wrapper a generic struct). https://github.com/gtk-rs/gir/pull/983 made gir generate code that doesn't pass this.

**Comment by bilelmoussaoui** [comment]
Never mind, I had a cached build of gir which caused this. It works fine! thanks

**Comment by sdroege** [comment]
Looks good to me, I'll merge this once gstreamer-rs is updated so we don't end up with something unbuildable for too long

**Comment by sdroege** [comment]
Also fixed gdkx11-sys, see https://github.com/gtk-rs/gir/issues/979

**Pull request merged**
