### PR TITLE
glib: Distinguish between classes and interfaces at the type level

### PR DESCRIPTION
**Pull request by sdroege**
Without this it was possible to cast from a Class<T> to a Class<U> where
U is an interface type. This doesn't work as interface structs are to be
retrieved differently than just casting and would cause memory unsafety
issues.

Fixes https://github.com/gtk-rs/gtk-rs/issues/348

### CODE REVIEW

**Comment by sdroege** [comment]
Maybe we should also distinguish further and have `glib::Class<T>` and `glib::Interface<T>` instead of using `glib::Class<T>` for both? Opinions?

**Comment by bilelmoussaoui** [comment]
> Maybe we should also distinguish further and have `glib::Class<T>` and `glib::Interface<T>` instead of using `glib::Class<T>` for both? Opinions?

Would there be any differences between  `Class<T>` & the future `Interface<T>` other than making them distinct?

**Comment by sdroege** [comment]
> Would there be any differences between `Class<T>` & the future `Interface<T>` other than making them distinct?

That and you can't really use any of the `Class` API on interfaces anyway (see this MR). It seems cleaner so I'm tending towards doing that.

**Comment by sdroege** [comment]
Also would be needed for proper reference counting for a `InterfaceRef` kind of type, so let's go with that

**Comment by GuillaumeGomez** [comment]
> Maybe we should also distinguish further and have `glib::Class<T>` and `glib::Interface<T>` instead of using `glib::Class<T>` for both? Opinions?

II think it'd be better to do it like this.

**Comment by sdroege** [comment]
Done, please review @bilelmoussaoui @GuillaumeGomez :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sdroege** [comment]
@bilelmoussaoui Also this needs some change in gtk4 so that stuff continues to compile (see gio commit here)

**Review by bilelmoussaoui — APPROVED** [review]

**Pull request merged**
