### PR TITLE
CI: docs generate index page and bump peaceiris/actions-gh-pages

### PR DESCRIPTION
**Pull request by jsparber**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Why did you add `-Zunstable-options` ?

**Comment by jsparber** [comment]
> Why did you add `-Zunstable-options` ?

because the `enable-index-page` is unstable, see: https://github.com/rust-lang/cargo/issues/8229#issuecomment-633153513

**Comment by GuillaumeGomez** [comment]
And what improvements are on this version of the action btw?

**Comment by jsparber** [comment]
> And what improvements are on this version of the action btw?

A year of development :) 
And in v3 the configuration is given via `with` not as environment variables, other then that not sure.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
