### PR TITLE
Rename glib_wrapper! and glib_object_subclass! to wrapper! and object_subclass!

### PR DESCRIPTION
**Pull request by ids1024**
I think it works quite nicely to use `glib::wrapper!` without having to `use` anything.

Also requires a gir change.

### CODE REVIEW

**Comment by sdroege** [comment]
There's even a issue for this: https://github.com/gtk-rs/gtk-rs/issues/168 :)

Are there any macros left that are prefixed?

**Comment by ids1024** [comment]
Grepping for `'macro_rules! glib'`, there's also `glib_boxed_wrapper!`, `glib_object_interface!`, `glib_bool_error!`, `glib_result_from_gboolean!`, `glib_shared_wrapper!`, `glib_weak_impl!`, `glib_object_wrapper!`.

I guess `glib_object_interface!` is part of the public non-hidden API and all(?) of the others aren't. But they could probably all be changed.

**Comment by sdroege** [comment]
> `glib_object_interface`
> `glib_bool_error`
> `glib_result_from_gboolean`

These are public and supposed to be used. Maybe the others could be prefixed with a couple of underscores or so to make it clearer that they're not "public" (well they are, but you're not supposed to use them directly...)

**Comment by sdroege** [comment]
Ok :) Do you want to prefix the other macros with `__` or keep it like this?

**Comment by ids1024** [comment]
I think a common idiom for this sort of thing would be a `#[doc(hidden)]` module named something like `private`. So it could be `glib::private::boxed_wrapper!`.

But it should be fine to merge this without a change like that.

**Comment by sdroege** [comment]
Yeah, fine for me to merge like this too. I just wasn't sure if you would like to do that change or not before getting it merged :)

**Review by sdroege — APPROVED** [review]

**Comment by ids1024** [comment]
Updated gir, and all checks are now passing.

**Review by GuillaumeGomez — APPROVED** [review]
Thanks!

**Pull request merged**
