### PR TITLE
Generate missing version constraints on automatic trait impls

### PR DESCRIPTION
**Pull request by MarijnS95**
With https://github.com/gtk-rs/gir/pull/1007

CC @GuillaumeGomez: This will conflict with #177, what do you want to merge in first? Your PR in gir is already merged (and theoretically mine is on top), I can rebase this when #177 lands.

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez @MarijnS95 Let's update gir once now and regenerate everything. There were a few minor other PRs for gir merged, let's do it all in one go :)

**Comment by GuillaumeGomez** [comment]
#177 is raising some issues so don't worry and go ahead.

**Comment by sdroege** [comment]
We can't regenerate without that one though because gir adds all the docs related changes

**Comment by GuillaumeGomez** [comment]
Yep sorry. I need to try to get @ehuss to let me add a setting in cargo to allow us to fix that situation.

**Comment by sdroege** [comment]
No problem :)

**Comment by GuillaumeGomez** [comment]
I'll make a more "global" regen including this one then. Thanks anyway!

**Pull request closed without merging**
