### PR TITLE
Update gir

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
CC @MarijnS95

**Comment by sdroege** [comment]
@bilelmoussaoui This should get rid of those unused doc comments things you noticed.

**Comment by MarijnS95** [comment]
This is pretty much https://github.com/gtk-rs/gtk-rs/pull/155 right? Except without enum changes? Don't forget to bump the MSRV when 1.48 drops :slightly_smiling_face:, I'll rebase afterwards.

**Comment by sdroege** [comment]
> This is pretty much #155 right? Except without enum changes? Don't forget to bump the MSRV when 1.48 drops slightly_smiling_face, I'll rebase afterwards.

Yeah, I want to get this in before all the enum changes are done so things are clean and the enum PR is smaller and easier to review.

I'll merge this one here once 1.48 is out

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by sdroege** [comment]
@MarijnS95 You can rebase :)

**Pull request merged**
